### ISSUE TITLE
dataset shareable?

### ISSUE THREAD

**Issue by 7LFB** [lonj7798/Liver_Fibrosis#1]
Dear Author,
It's excited to see your release code focusing on liver fibrosis staging.  Is dataset available? Or do I need to provide any documents to access dataset? Thank you!

**Comment by lonj7798** [comment]
> Dear Author, It's excited to see your release code focusing on liver fibrosis staging. Is dataset available? Or do I need to provide any documents to access dataset? Thank you!

Hello 7LFB.
Thank you for your interest in the dataset! I'm sorry to say that the dataset is not sharable as it does not belong to me.

**Comment by 7LFB** [comment]
> 

thanks anyway！
